name: Build and Test ASP.NET # The name of the workflow

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main # Trigger the workflow on pull request to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Check out the repository code

    - name: Setup .NET
      uses: actions/setup-dotnet@v3 # Set up the .NET environment
      with:
        dotnet-version: '8' # Specify the .NET version to use

    - name: Install dependencies
      run: dotnet restore # Restore the dependencies

    - name: Build
      run: dotnet build --configuration Release --no-restore # Build the application in Release configuration

    - name: Test
      run: dotnet test --no-restore --verbosity normal # Run the tests with normal verbosity

    - name: Azure Login
      uses: Azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDS }}
          
    - name: Create image
      run: az acr build -r demo68365 --image demo-webapp-68365:v1 .

    - name: Deploy Bicep template in Dev
      run: az deployment group create --name DeployToDevFromGitHub --resource-group Demo68365  --template-file ./bicep/template.bicep --parameters ./bicep/parameters-dev.json

    # - name: Deploy web app
      